### ISSUE TITLE
Should I migrate off of this?

### ISSUE THREAD

**Issue by ilyakamens** [JustinVoitel/svelte-hero-icons#37]
Hi,

I'm taking over a new project that uses this library. I see the following at the top of the README:

>If you want to use more Icons Packs and components for multiple Frameworks (React, Vue, Lit and more), check out [@steeze-ui/icons](https://github.com/steeze-ui/icons) which is meant as a successor to svelte-hero-icons:

Will your repository no longer be maintained in the near future? Should I switch off of this and use the library you linked to? Thanks.

**Comment by JustinVoitel** [comment]
[svelte-hero-icons](https://github.com/JustinVoitel/svelte-hero-icons) uses [@steeze-ui/icons](https://github.com/steeze-ui/icons) under the hood but features a different API (e.g the solid, mini, micro properties). It is still maintained for new [tailwindlabs/heroicons](https://github.com/tailwindlabs/heroicons) versions but might get the updates later.  

There shouldn`t be a problem in using it further!

But for a new Project I would recommend to use the `@steeze-ui/svelte-icon` and `@steeze-ui/heroicons` packages since it is maintained more frequently and you can use many popular Icon Sets (e.g simple-icons, tabler-icons, material-icons etc) using the same API.
