### ISSUE TITLE
Dynamic import example

### ISSUE THREAD

**Issue by wiesson** [JustinVoitel/svelte-hero-icons#6]
I'm wondering if we could lazy load icons by prop name on mount:

```Javascript
export let icon; // desired icon name

onMount(async () => {
  const { default: Icon } = await import(`svelte-hero-icons`); // does somehow not work on sveltekit
})
```

**Comment by JustinVoitel** [comment]
yea I already tried this approach some weeks ago, this was my code:
```js
onMount(async () => {
   let res = await import(`./heroicons/hero-${src}.json`).then(
     ({ default: res }) => res
   );
   icon = res;
 });
```
dev worked perfectly and it was only importing the stuff wanted, but when bundling for production it didn't include the json data in `build/assets/_app/chunks/[iconname].json`. 

Even more weirdly that if I hardcoded the icon name into the snippet above, e.g:
```js
await import(`./heroicons/hero-ArrowUp.json`)
```
The build would include it exactly as I want it. I'm guessing it has something to do with  [@rollup/plugin-dynamic-import-vars](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations) which vite uses under the hood. 

I stopped digging deeper because I think in this early stage of both projects a lot will change and might make this possible in the future. 
Though I kinda like how the API is now but I'm open to try other ways :) PR's welcome!
